config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root to: 'cocktails#index'
  resources :cocktails do
    resources :doses, only: [:new, :create]
  end
  resources :doses, only: [:show]
  delete 'doses/:id', to: 'doses#destroy'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/cocktail.rb
class Cocktail < ApplicationRecord
  has_many :doses, dependent: :destroy
  has_many :ingredients, through: :doses
  has_one_attached :photo

  validates :name, presence: true, uniqueness: true
end

app/models/dose.rb
class Dose < ApplicationRecord
  belongs_to :cocktail
  belongs_to :ingredient

  validates :cocktail_id, presence: true
  validates :ingredient_id, presence: true
  validates :description, presence: true
  validates_uniqueness_of :cocktail_id, scope: :ingredient_id
end

app/models/ingredient.rb
class Ingredient < ApplicationRecord
  has_many :doses

  validates :name, presence: true, uniqueness: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/cocktails_controller.rb
class CocktailsController < ApplicationController
  def index
    @cocktails = Cocktail.all
  end

  def show
    @cocktail = Cocktail.find(params[:id])
  end

  def new
    @cocktail = Cocktail.new
  end

  def create
    @cocktail = Cocktail.new(cocktail_params)
    if @cocktail.save
      redirect_to cocktail_path(@cocktail.id)
    else
      render :new
    end
  end

  def edit
    @cocktail = Cocktail.find(params[:id])
  end

  def update
    @cocktail = Cocktail.find(params[:id])
    @cocktail.update(cocktail_params)
    @cocktail.save
    redirect_to cocktail_path(@cocktail.id)
  end

  def destroy
    @cocktail = Cocktail.find(params[:id])
    @cocktail.delete
    redirect_to root_path
  end

  private

  def cocktail_params
    params.require(:cocktail).permit(:name, :photo)
  end
end

app/controllers/doses_controller.rb
class DosesController < ApplicationController
  def show
    @dose = Dose.find(params[:id])
    @cocktail = @dose.cocktail
    @doses = @cocktail.doses
  end

  def new
    @cocktail = Cocktail.find(params[:cocktail_id])
    @dose = Dose.new
  end

  def create
    @cocktail = Cocktail.find(params[:cocktail_id])
    @dose = Dose.new(dose_params)
    @dose.cocktail = @cocktail
    # @ingredient = Ingredient.find(params[:ingredient_id])
    if @dose.save
      redirect_to cocktail_path(@cocktail.id)
    else
      render :new
    end
  end

  def destroy
    @dose = Dose.find(params[:id])
    @dose.delete
    redirect_to root_path
  end

  private

  def dose_params
    params.require(:dose).permit(:description, :cocktail_id, :ingredient_id)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/cocktails_helper.rb
module CocktailsHelper
end

app/helpers/doses_helper.rb
module DosesHelper
end

app/views/cocktails/edit.html.erb
<h1 class="text-center"> Edit <%= @cocktail.name %></h1>

<%= render 'shared/cocktail_form' %>

<%= link_to 'Back To Cocktail', cocktail_path(@cocktail), class: "btn btn-outline-secondary mt-2" %>

app/views/cocktails/index.html.erb
<h1 class="text-center">Cocktails</h1>
<div class="d-flex flex-wrap cocktail-box">
<% @cocktails.each do |cocktail| %>
  <div class="card m-2 d-flex">
    <% if cocktail.photo.attached? %>
      <%= cl_image_tag cocktail.photo.key, class: 'card-img-top card-image' %>
    <% end %>
    <div class="card-body">
      <h5 class="card-title"><%= cocktail.name %></h5>
      <%= link_to 'Discover more', cocktail_path(cocktail), class: "btn btn-outline-secondary" %>
    </div>
  </div>
<% end %>
</div>

app/views/cocktails/new.html.erb
<h1 class="text-center">Add New Cocktail</h1>

<%= render 'shared/cocktail_form' %>

app/views/cocktails/show.html.erb
<div class="cocktail-container">
  <h1 class="cocktail-name text-center mb-5"><%= @cocktail.name %></h1>
  <div class="cocktail-details">
    <ul>
      <h5 class="cocktail-doses">Ingredients</h5>
      <% @cocktail.doses.each do |dose| %>
        <li class="cocktail-doses"><%= dose.description %> - <%= dose.ingredient.name %></li>
      <% end %>
    </ul>
    <% if @cocktail.photo.attached? %>
      <%= cl_image_tag @cocktail.photo.key, height: 400, width:400, crop: :fill, class: 'show-image' %>
    <% end %>
  </div>
  <div class="show-links">
    <%= link_to 'Add ingredients', new_cocktail_dose_path(@cocktail.id), class: 'btn btn-outline-secondary' %>
    <%= link_to 'Edit Cocktail', edit_cocktail_path(@cocktail.id), class: 'btn btn-outline-secondary' %>
    <%= link_to 'Delete Cocktail', cocktail_path(@cocktail.id), method: :delete, data: { confirm: 'Are you sure?' }, class: 'btn btn-outline-secondary delete-btn' %>
  </div>
</div>

app/views/doses/new.html.erb
<h1>New Ingredients For <%= @cocktail.name %></h1>

<%= simple_form_for [@cocktail, @dose] do |f| %>
  <%= f.association :cocktail, input_html: { class: 'input' } %>
  <%= f.association :ingredient, input_html: { class: 'input' } %>
  <%= f.input :description, input_html: { class: 'input' } %>
  <%= f.button :submit, input_html: { class: 'submit' } %>
<% end %>

<%= link_to 'Back To Cocktail', cocktail_path(@cocktail), class: "btn btn-outline-secondary mt-2" %>

app/views/doses/show.html.erb
<h1 class="text-center">Doses for <%= @dose.cocktail.name %></h1>
<% @doses.each do |dose| %>
  <p><%= dose.description %> | <%= dose.ingredient.name %></p>
  <%= link_to "Delete Ingredient", dose_path(dose.id), method: :delete, data: { confirm: 'Are you sure?' } %>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Mr. Cocktails World | A Rails App</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render 'shared/navbar' %>
    <div class="container main">
      <%= yield %>
    </div>
  </body>
</html>

app/views/shared/_cocktail_form.html.erb
<%= simple_form_for @cocktail do |f| %>
  <%= f.input :name, input_html: { class: 'input' }%>
  <label class="btn submit">
    Add a photo
    <span style="display:none;">
      <%= f.input :photo, as: :file %>
    </span>
  </label> <br>
  <%= f.button :submit, input_html: { class: 'submit' } %>
<% end %>

app/views/shared/_navbar.html.erb
<div class="navbar navbar-expand-sm navbar-light navbar-lewagon">
  <%= link_to root_path, class: "navbar-brand" do %>
    <h5 class="nav-logo">Mr Cocktails World</h5>
  <% end %>

  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon" id="burger"><i class="fas fa-bars"></i></span>
  </button>


  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <li class="nav-item">
        <%= link_to "Cocktails", cocktails_path, class: "nav-link my-2 p-1", id: "navbar-text" %>
      </li>
      <li class="nav-item">
        <%= link_to "Add Cocktail", new_cocktail_path, class: "nav-link my-2 p-1", id: "navbar-text" %>
      </li>
    </ul>
  </div>
</div>